name: Packager

env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
   
    - name: Update apt
      run: sudo apt update
    
    - name: Set up media prerequisites
      run: sudo apt install -y pkg-config build-essential libopusfile-dev libfdk-aac-dev libavutil-dev libavcodec-dev libswscale-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build

    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: rtmp-ingest
        path: rtmp-ingest